import assert from "node:assert/strict";
import { createHash } from "node:crypto";
await import("../../public/js/master-model.js");
const model = globalThis.PortfolioMasterModel;
const copy = (value) => structuredClone(value);

const product = {
  id: "p1", name: "Cloud Team", codename: "Together", price: 99.99, priceLabel: "$99.99", tier: "Premium", statusType: "new", statusLabel: "New product", variantLabel: "PC",
  generalAvailabilityDate: "2026-03-20", ffsDate: "2026-02-18", endManufacturingDate: "2028-12-10", globalAnnouncementDate: "2026-03-01", webReadinessDate: "2026-03-10", finalAssetsDate: "2026-02-20",
  roadmap: { startMonth: "2026-03", launchMonth: "2026-03", endMonth: "2028-12", family: "Cloud", status: "in-development", confidence: "high", notes: "Keep local notes" },
  imageAssetId: "local-main", featuredVariantId: "black", laneId: "lane-local", manualMetadata: "Keep product extras",
  specs: [{ id: "connection", label: "Connection", value: "USB", manualNote: "Keep spec extras" }, { id: "driver", label: "Driver", value: "53 mm" }],
  partSkus: [{ id: "sku1", code: "HP001", variantId: "black", manualNote: "Keep part extras" }],
  variantGroups: [{ id: "colors", type: "color", label: "COLOR SKU", customSetting: true, items: [{ id: "black", code: "BK", colorKey: "black", colorName: "Black", colorHex: "#111111", imageAssetId: "local-black" }] }],
};
const manifest = { version: 2, packageInfo: { id: "package-one" }, categories: [{ id: "audio", board: { products: [product], lanes: [{ id: "lane-local" }] } }], imageAssets: [{ id: "local-main" }, { id: "local-black" }] };
const before = copy(manifest);
const base = model.values(product);
const change = (patch, values = base, revisions = {}) => ({ productId: "p1", base: values, baseRevisions: revisions, patch });
const save = (current, patch, values = base, revisions = {}) => model.mergeChanges(current, [change(patch, values, revisions)], { actor: "Alex", team: "Operations", reason: "Factory update", now: "2026-10-07T17:00:00Z", requestId: "request-one" });
const savedProduct = (result) => result.manifest.categories[0].board.products[0];

assert.equal(base.imageAssetId, undefined);
assert.equal(base.variantGroups[0].items[0].imageAssetId, undefined);
assert.equal(base.specs[0].manualNote, undefined);
assert.equal(base.startMonth, "2026-03");
assert.equal(base.roadmapFamily, "Cloud");
assert.equal(model.snapshot(manifest).products[0].productName, "Cloud Team");

const launch = save(manifest, { generalAvailabilityDate: "2026-07-31" });
assert.equal(launch.savedFields, 1, "launch date/month must save as one logical unit");
assert.equal(savedProduct(launch).generalAvailabilityDate, "2026-07-31");
assert.equal(savedProduct(launch).roadmap.startMonth, "2026-07");
assert.equal(savedProduct(launch).roadmap.launchMonth, "2026-07");
assert.equal(launch.history[0].path, "@launch");
assert.equal(launch.history[0].requestId, "request-one");
assert.deepEqual(manifest, before, "merging must never mutate the original master");

const tbd = save(manifest, { generalAvailabilityDate: "TBD", startMonth: "2026-09" });
assert.equal(savedProduct(tbd).generalAvailabilityDate, "");
assert.equal(savedProduct(tbd).roadmap.startMonth, "2026-03", "clearing the exact day must retain the prior planning month");
const moveMonth = save(manifest, { startMonth: "2026-06" });
assert.equal(savedProduct(moveMonth).generalAvailabilityDate, "2026-06-20");
assert.equal(savedProduct(moveMonth).roadmap.startMonth, "2026-06");
const january = model.patchValues(base, { generalAvailabilityDate: "2027-01-31" });
assert.equal(model.patchValues(january, { startMonth: "2027-02" }).generalAvailabilityDate, "2027-02-28", "month-only edits must preserve/clamp the known day");
assert.equal(model.patchValues(base, { endManufacturingDate: "" }).endMonth, "2028-12");

for (const field of model.DATE_FIELDS) {
  assert.throws(() => save(manifest, { [field]: "2026-02-30" }), /real calendar date/);
  assert.throws(() => save(manifest, { [field]: "10/07/2026" }), /YYYY-MM-DD/);
}
assert.throws(() => save(manifest, { startMonth: "2026-13" }), /YYYY-MM/);
assert.throws(() => save(manifest, { generalAvailabilityDate: "2029-01-01" }), /on or after launch/);
assert.throws(() => save(manifest, { price: -1 }), /non-negative/);
assert.throws(() => save(manifest, { imageAssetId: "remote-image" }), /Unsupported shared field/);

const allMilestones = save(manifest, { ffsDate: "2026-02-19", globalAnnouncementDate: "2026-03-02", webReadinessDate: "2026-03-11", finalAssetsDate: "2026-02-21" });
assert.equal(allMilestones.savedFields, 4);
assert.equal(savedProduct(allMilestones).imageAssetId, product.imageAssetId);
assert.equal(savedProduct(allMilestones).roadmap.notes, product.roadmap.notes);
assert.equal(savedProduct(allMilestones).laneId, product.laneId);
assert.deepEqual(allMilestones.manifest.imageAssets, manifest.imageAssets);

const masterSpec = save(manifest, { specs: base.specs.map((row) => row.id === "connection" ? { ...row, value: "USB-C" } : row) });
const localSpec = base.specs.map((row) => row.id === "driver" ? { ...row, value: "55 mm" } : row);
const combinedSpecs = save(masterSpec.manifest, { specs: localSpec });
assert.equal(combinedSpecs.conflicts.length, 0);
assert.equal(savedProduct(combinedSpecs).specs[0].value, "USB-C");
assert.equal(savedProduct(combinedSpecs).specs[1].value, "55 mm");
assert.equal(savedProduct(combinedSpecs).specs[0].manualNote, "Keep spec extras");
const renameSpec = save(masterSpec.manifest, { specs: base.specs.map((row) => row.id === "connection" ? { ...row, label: "Connector" } : row) });
assert.equal(renameSpec.conflicts.length, 0, "label and value changes on the same spec must combine");
assert.equal(savedProduct(renameSpec).specs[0].label, "Connector");
assert.equal(savedProduct(renameSpec).specs[0].value, "USB-C");
const conflictingSpec = save(masterSpec.manifest, { specs: base.specs.map((row) => row.id === "connection" ? { ...row, value: "Bluetooth" } : row) });
assert.equal(conflictingSpec.savedFields, 0);
assert.equal(conflictingSpec.manifest, masterSpec.manifest);
assert.equal(conflictingSpec.conflicts[0].path, "specs/connection/value");
assert.equal(conflictingSpec.conflicts[0].mine, "Bluetooth");
assert.equal(conflictingSpec.conflicts[0].master, "USB-C");

const masterSku = save(manifest, { partSkus: [...base.partSkus, { id: "sku2", code: "HP002" }] });
const combinedSku = save(masterSku.manifest, { partSkus: [...base.partSkus, { id: "sku3", code: "HP003" }] });
assert.equal(combinedSku.conflicts.length, 0);
assert.deepEqual(savedProduct(combinedSku).partSkus.map((row) => row.code), ["HP001", "HP002", "HP003"]);
const assignSku = save(manifest, { partSkus: base.partSkus.map((row) => ({ ...row, variantId: "white" })) });
const skuCodeAndColor = save(assignSku.manifest, { partSkus: base.partSkus.map((row) => ({ ...row, code: "HP001-REV" })) });
assert.equal(skuCodeAndColor.conflicts.length, 0);
assert.equal(savedProduct(skuCodeAndColor).partSkus[0].variantId, "white");
assert.equal(savedProduct(skuCodeAndColor).partSkus[0].manualNote, "Keep part extras");
const skuSameProperty = save(masterSku.manifest, { partSkus: base.partSkus.map((row) => ({ ...row, code: "HP001-REV" })) });
const skuSameAgain = save(skuSameProperty.manifest, { partSkus: base.partSkus.map((row) => ({ ...row, code: "HP001-FINAL" })) });
assert.equal(skuSameAgain.conflicts[0].path, "partSkus/sku1/code");

const duplicateAdd = save(masterSku.manifest, { partSkus: [...base.partSkus, { id: "different-id", code: "hp002" }] });
assert.equal(duplicateAdd.conflicts.length, 1);
assert.equal(duplicateAdd.conflicts[0].reason, "duplicate-sku");
const duplicateMine = model.patchValues(base, { partSkus: [...base.partSkus, { id: "different-id", code: "hp002" }] });
const duplicatePlan = model.planMerge(base, duplicateMine, model.values(savedProduct(masterSku)));
const keepMySku = model.resolveConflicts(duplicatePlan, { [duplicatePlan.conflicts[0].path]: "mine" });
const keepMasterSku = model.resolveConflicts(duplicatePlan, { [duplicatePlan.conflicts[0].path]: "master" });
assert.deepEqual(keepMySku.partSkus.map((row) => row.id), ["sku1", "different-id"]);
assert.deepEqual(keepMasterSku.partSkus.map((row) => row.id), ["sku1", "sku2"]);
assert.throws(() => save(manifest, { partSkus: [...base.partSkus, { id: "dup", code: "hp001" }] }), /same SKU code/);
const duplicateBaseline = model.draftBaseline(base, duplicateMine, model.values(savedProduct(masterSku)));
assert.equal(duplicateBaseline.partSkus.some((row) => row.id === "sku2"), false);
const duplicateStillNeedsChoice = save(masterSku.manifest, model.diffValues(duplicateBaseline, keepMySku), duplicateBaseline);
assert.equal(duplicateStillNeedsChoice.conflicts[0].reason, "duplicate-sku", "refresh must never implicitly approve replacing another team's colliding SKU");

const variantsMine = copy(base.variantGroups);
variantsMine[0].items[0].colorName = "Midnight";
const variantColorMaster = copy(base.variantGroups);
variantColorMaster[0].items[0].colorHex = "#222222";
const variantMaster = save(manifest, { variantGroups: variantColorMaster });
const variantCombined = save(variantMaster.manifest, { variantGroups: variantsMine });
assert.equal(variantCombined.conflicts.length, 0);
assert.equal(savedProduct(variantCombined).variantGroups[0].items[0].colorName, "Midnight");
assert.equal(savedProduct(variantCombined).variantGroups[0].items[0].colorHex, "#222222");
assert.equal(savedProduct(variantCombined).variantGroups[0].items[0].imageAssetId, "local-black");
assert.equal(savedProduct(variantCombined).variantGroups[0].customSetting, true);
const variantConflicting = copy(base.variantGroups);
variantConflicting[0].items[0].colorHex = "#333333";
assert.equal(save(variantMaster.manifest, { variantGroups: variantConflicting }).conflicts[0].path, "variantGroups/colors/items/black/colorHex");

const addVariantMaster = copy(base.variantGroups);
addVariantMaster[0].items.push({ id: "white", code: "WHT", colorName: "White" });
const addVariantMine = copy(base.variantGroups);
addVariantMine[0].items.push({ id: "blue", code: "BLU", colorName: "Blue" });
const differentVariantAdds = save(save(manifest, { variantGroups: addVariantMaster }).manifest, { variantGroups: addVariantMine });
assert.deepEqual(savedProduct(differentVariantAdds).variantGroups[0].items.map((row) => row.id), ["black", "white", "blue"]);
const collisionVariant = copy(base.variantGroups);
collisionVariant[0].items.push({ id: "white-other", code: "wht", colorName: "White" });
assert.equal(save(save(manifest, { variantGroups: addVariantMaster }).manifest, { variantGroups: collisionVariant }).conflicts[0].reason, "duplicate-sku");

const removalAgainstEdit = save(masterSpec.manifest, { specs: base.specs.filter((row) => row.id !== "connection") });
assert.equal(removalAgainstEdit.conflicts[0].path, "specs/connection");
assert.equal(removalAgainstEdit.conflicts[0].mineExists, false);
const removedSpec = save(manifest, { specs: base.specs.filter((row) => row.id !== "connection") });
const editAgainstRemoval = save(removedSpec.manifest, { specs: base.specs.map((row) => row.id === "connection" ? { ...row, value: "Wireless" } : row) });
assert.equal(editAgainstRemoval.conflicts[0].path, "specs/connection");
assert.equal(editAgainstRemoval.conflicts[0].masterExists, false);
const restoredPlan = model.planMerge(base, model.patchValues(base, { specs: base.specs.map((row) => row.id === "connection" ? { ...row, value: "Wireless" } : row) }), model.values(savedProduct(removedSpec)));
assert.equal(model.resolveConflicts(restoredPlan, { "specs/connection": "mine" }).specs[1].value, "Wireless", "keeping a changed row must restore the full record");
assert.equal(model.resolveConflicts(restoredPlan, { "specs/connection": "master" }).specs.some((row) => row.id === "connection"), false);
const removeGroupMaster = save(manifest, { variantGroups: [] });
assert.equal(save(removeGroupMaster.manifest, { variantGroups: variantsMine }).conflicts[0].path, "variantGroups/colors");

const sameAddedIdMaster = save(manifest, { specs: [...base.specs, { id: "same-new-id", label: "Battery", value: "20 h" }] });
const sameAddedIdConflict = save(sameAddedIdMaster.manifest, { specs: [...base.specs, { id: "same-new-id", label: "Battery", value: "30 h" }] });
assert.equal(sameAddedIdConflict.conflicts[0].path, "specs/same-new-id");
assert.equal(save(sameAddedIdMaster.manifest, { specs: [...base.specs, { id: "same-new-id", label: "Battery", value: "20 h" }] }).savedFields, 0, "converged additions are no-ops");

const remoteLaunch = model.snapshot(launch.manifest).products[0];
const launchAgain = save(launch.manifest, { generalAvailabilityDate: "2026-08-15" });
assert.equal(launchAgain.conflicts[0].path, "@launch");
assert.equal(save(launch.manifest, { generalAvailabilityDate: "2026-07-31" }).savedFields, 0, "same final value must converge even with old revisions");
const rebasePlan = model.planMerge(base, model.patchValues(base, { generalAvailabilityDate: "2026-08-15" }), remoteLaunch.values, {}, remoteLaunch.revisions);
const explicitFinal = model.resolveConflicts(rebasePlan, { "@launch": "mine" });
const explicitSaved = save(launch.manifest, model.diffValues(remoteLaunch.values, explicitFinal), remoteLaunch.values, remoteLaunch.revisions);
assert.equal(explicitSaved.conflicts.length, 0);
assert.equal(savedProduct(explicitSaved).generalAvailabilityDate, "2026-08-15");

const launchBack = save(launch.manifest, { generalAvailabilityDate: base.generalAvailabilityDate }, remoteLaunch.values, remoteLaunch.revisions);
const aba = save(launchBack.manifest, { generalAvailabilityDate: "2026-09-01" });
assert.equal(aba.conflicts[0].path, "@launch", "changing away and back must retain a revision conflict");
const removedSnapshot = model.snapshot(removedSpec.manifest).products[0];
const readdedSpec = save(removedSpec.manifest, { specs: base.specs }, removedSnapshot.values, removedSnapshot.revisions);
assert.equal(save(readdedSpec.manifest, { specs: base.specs.map((row) => row.id === "connection" ? { ...row, value: "USB4" } : row) }).conflicts[0].path, "specs/connection/value", "remove/re-add ABA must block an old property edit");

const shortEndMaster = save(manifest, { endManufacturingDate: "2026-06-01" });
const incompatibleLaunch = model.patchValues(base, { generalAvailabilityDate: "2026-07-01" });
const orderPlan = model.planMerge(base, incompatibleLaunch, model.values(savedProduct(shortEndMaster)));
assert.equal(orderPlan.conflicts[0].path, "@lifecycle");
assert.equal(model.resolveConflicts(orderPlan, { "@lifecycle": "mine" }).endManufacturingDate, base.endManufacturingDate);
assert.equal(model.resolveConflicts(orderPlan, { "@lifecycle": "master" }).generalAvailabilityDate, base.generalAvailabilityDate);
const orderBaseline = model.draftBaseline(base, incompatibleLaunch, model.values(savedProduct(shortEndMaster)));
assert.equal(orderBaseline.endManufacturingDate, base.endManufacturingDate, "local lifecycle preview must preserve original origins for a future conflict decision");
const bothDateMaster = save(manifest, { generalAvailabilityDate: "2026-04-01", endManufacturingDate: "2026-06-01" });
assert.equal(model.planMerge(base, incompatibleLaunch, model.values(savedProduct(bothDateMaster))).conflicts[0].path, "@lifecycle", "unsafe possible field choices must be presented as one valid lifecycle pair");

const draftMine = model.patchValues(base, { specs: localSpec });
const draftRemote = model.values(savedProduct(masterSpec));
const draftBase = model.draftBaseline(base, draftMine, draftRemote);
assert.equal(draftBase.specs[0].value, "USB-C", "unrelated accepted spec updates become the new baseline");
assert.equal(draftBase.specs[1].value, "53 mm", "unsaved spec edits retain their original baseline");
assert.deepEqual(model.diffValues(draftBase, model.resolveConflicts(model.planMerge(base, draftMine, draftRemote))), { specs: [{ ...base.specs[0], value: "USB-C" }, localSpec[1]] });
assert.deepEqual(model.diffValues(model.draftBaseline(base, draftRemote, draftRemote), draftRemote), {}, "remote convergence must clear the unsaved marker");
const draftRevs = model.draftRevisions(base, draftMine, {}, { "specs/connection/value": 2, "specs/driver/value": 3 });
assert.equal(draftRevs["specs/connection/value"], 2);
assert.equal(draftRevs["specs/driver/value"], 0);
assert.equal(model.describeChanges(base, draftMine)[0].label, "Specification: Driver — Value");
assert.equal(model.describeChanges(base, draftMine)[0].mineText, "55 mm");

assert.throws(() => save(manifest, { specs: [{ id: "__proto__", label: "Danger", value: "x" }] }), /stable ID/);
assert.throws(() => model.snapshot({ categories: [{ board: { products: [{ id: "p" }, { id: "p" }] } }] }), /duplicate product IDs/);
assert.throws(() => model.mergeChanges(manifest, [change({ name: "One" }), change({ name: "Two" })]), /only once/);
assert.equal(model.mergeChanges(manifest, [{ ...change({ name: "One" }), productId: "not-in-master" }]).conflicts[0].reason, "product-removed");
assert.throws(() => model.mergeChanges(manifest, Array.from({ length: 501 }, () => change({ name: "One" }))), /at most 500/);
const suspiciousRevisions = JSON.parse('{"__proto__": 3,"constructor": 4,"name": 0}');
assert.equal(save(manifest, { name: "Safe" }, base, suspiciousRevisions).conflicts.length, 0);
assert.equal({}.polluted, undefined);

const escapedProduct = copy(product);
escapedProduct.specs[0].id = "connection/a b";
const escapedManifest = copy(manifest);
escapedManifest.categories[0].board.products[0] = escapedProduct;
const escapedBase = model.values(escapedProduct);
const escapedResult = save(escapedManifest, { specs: escapedBase.specs.map((row) => row.id === "connection/a b" ? { ...row, value: "USB5" } : row) }, escapedBase);
assert.equal(escapedResult.history[0].path, "specs/connection%2Fa%20b/value");

const scalarMaster = save(manifest, { name: "New product name", codename: "New codename", price: 109.99, priceLabel: "Suggested price", tier: "Core", statusType: "embargo", statusLabel: "Upcoming under embargo", variantLabel: "PLAYSTATION", roadmapFamily: "Flight", roadmapStatus: "in-planning", roadmapConfidence: "medium", roadmapPredecessorId: "older-product", roadmapSuccessorId: "newer-product" });
assert.equal(scalarMaster.savedFields, 13);
assert.equal(savedProduct(scalarMaster).name, "New product name");
assert.equal(savedProduct(scalarMaster).roadmap.family, "Flight");
assert.equal(savedProduct(scalarMaster).roadmap.predecessorId, "older-product");
assert.equal(savedProduct(scalarMaster).imageAssetId, "local-main");
assert.equal(save(scalarMaster.manifest, { name: "Another name" }).conflicts[0].path, "name");
const independentScalar = save(save(manifest, { name: "Name accepted" }).manifest, { price: 129.99 });
assert.equal(independentScalar.conflicts.length, 0);
assert.equal(savedProduct(independentScalar).name, "Name accepted");
assert.equal(savedProduct(independentScalar).price, 129.99);

const multiProduct = copy(launch.manifest);
multiProduct.categories[0].board.products.push({ ...copy(product), id: "p2", name: "Second product" });
const atomicResult = model.mergeChanges(multiProduct, [change({ generalAvailabilityDate: "2026-08-01" }), { productId: "p2", base: model.values(multiProduct.categories[0].board.products[1]), patch: { name: "Should wait" } }]);
assert.equal(atomicResult.manifest, multiProduct);
assert.equal(atomicResult.savedProducts, 0);
assert.equal(atomicResult.manifest.categories[0].board.products[1].name, "Second product", "a conflict must hold every product in that save until final choices are made");

const metadataWithOnlyPaths = copy(manifest);
metadataWithOnlyPaths.masterSync = { products: { p1: { revisions: { ffsDate: 100 } } } };
const continuedCounter = save(metadataWithOnlyPaths, { name: "Next revision" });
assert.equal(continuedCounter.history[0].revision, 101, "snapshot metadata exported without its global clock must not reuse old revision numbers");

const manyHistory = copy(manifest);
manyHistory.masterSync = { history: Array.from({ length: 1000 }, (_, index) => ({ path: "specs/large/value", before: "x".repeat(16000), after: "y".repeat(16000), index })) };
const historyResult = save(manyHistory, { name: "History cap" });
assert.ok(historyResult.manifest.masterSync.history.length < 1000);
assert.ok(JSON.stringify(historyResult.manifest.masterSync.history).length * 2 < 530000);
assert.equal(historyResult.manifest.masterSync.history.at(-1).after, "History cap");

const canonicalJson = (value) => JSON.stringify((function stable(item) { return Array.isArray(item) ? item.map(stable) : item && typeof item === "object" ? Object.fromEntries(Object.keys(item).sort().map((key) => [key, stable(item[key])])) : item; })(value));
assert.equal(model.productVersion(product), createHash("sha256").update(canonicalJson(product)).digest("hex"), "the full-record version must be a standard SHA-256 fingerprint");
for (const item of [{}, { name: "中文 🎧 Việt Nam" }, { note: "Multiblock value".repeat(1000) }]) assert.equal(model.productVersion(item), createHash("sha256").update(canonicalJson(item)).digest("hex"));
assert.equal(model.productVersion({ ...copy(product), name: "Cloud Team" }), model.productVersion(product));
assert.equal(model.productVersion({ name: product.name, ...copy(product) }), model.productVersion(product), "object property order must not produce a spurious product change");
assert.notEqual(model.productVersion({ ...product, manualMetadata: "Changed outside shared fields" }), model.productVersion(product));
const placement = model.snapshot(manifest).products[0];
assert.equal(placement.categoryId, "audio");
assert.equal(placement.laneId, "lane-local");
assert.equal(placement.productVersion, model.productVersion(product));

const createProduct = (productId = "new-product", mine = { ...base, name: "New shared product" }, extra = {}) => ({ kind: "create", productId, categoryId: "audio", laneId: "lane-local", mine, ...extra });
const deleteProduct = (entry = placement) => ({ kind: "delete", productId: entry.productId, categoryId: entry.categoryId, laneId: entry.laneId, base: copy(entry.values), baseRevisions: copy(entry.revisions), baseProductVersion: entry.productVersion });
const created = model.mergeChanges(manifest, [createProduct()], { requestId: "create-request", actor: "Product team" });
assert.equal(created.savedFields, 1);
assert.equal(created.savedProducts, 1);
assert.equal(created.history[0].path, "@product");
assert.equal(created.history[0].kind, "create");
assert.equal(created.history[0].beforeExists, false);
assert.equal(created.history[0].afterExists, true);
assert.equal(created.manifest.categories[0].board.products[1].id, "new-product");
assert.equal(created.manifest.categories[0].board.products[1].laneId, "lane-local");
assert.equal(created.manifest.categories[0].board.products[1].order, 0);
assert.equal(created.manifest.categories[0].board.products[1].generalAvailabilityDate, base.generalAvailabilityDate);
assert.deepEqual(created.manifest.imageAssets, manifest.imageAssets);
assert.deepEqual(created.manifest.categories[0].board.products[0], product, "creating another product must preserve the complete existing record");
assert.deepEqual(manifest, before, "lifecycle merging must never mutate its input");
const createReplay = model.mergeChanges(created.manifest, [createProduct()], { requestId: "create-request" });
assert.equal(createReplay.savedProducts, 0, "replaying an already accepted create request must not create a second record");
assert.equal(createReplay.manifest, created.manifest);
const idCollision = model.mergeChanges(created.manifest, [createProduct()], { requestId: "different-request" });
assert.equal(idCollision.conflicts[0].reason, "product-id-exists");
assert.equal(idCollision.conflicts[0].path, "@product");
assert.equal(idCollision.conflicts[0].baseExists, false);
assert.equal(idCollision.conflicts[0].mineExists, true);
assert.equal(idCollision.conflicts[0].masterExists, true);
assert.equal(idCollision.savedProducts, 0);
assert.equal(idCollision.manifest, created.manifest);
assert.throws(() => model.mergeChanges(manifest, [createProduct("new-product", base, { categoryId: "missing-portfolio" })]), /portfolio is no longer/);
assert.throws(() => model.mergeChanges(manifest, [createProduct("new-product", base, { laneId: "missing-lane" })]), /lane is no longer/);
assert.throws(() => model.mergeChanges(manifest, [createProduct("new-product", { ...base, imageAssetId: "private-image" })]), /Unsupported shared field/);
assert.throws(() => model.mergeChanges(manifest, [createProduct("new-product", { ...base, generalAvailabilityDate: "2026-02-31" })]), /real calendar date/);
assert.throws(() => model.mergeChanges(manifest, [createProduct(), createProduct()]), /only once/);
assert.throws(() => model.mergeChanges(manifest, [{ ...change({ name: "Unknown mode" }), kind: "replace" }]), /update, create, delete, or merge/);

const twoPortfolios = copy(manifest);
twoPortfolios.categories.push({ id: "console", board: { products: [], lanes: [{ id: "console-lane" }] } });
const consoleCopy = model.mergeChanges(twoPortfolios, [createProduct("console-copy", base, { categoryId: "console", laneId: "console-lane" })]);
assert.equal(consoleCopy.conflicts.length, 0, "the same product name and SKUs can be listed in separate PC and Console portfolios");
assert.equal(consoleCopy.manifest.categories[1].board.products[0].name, product.name);
assert.equal(consoleCopy.manifest.categories[1].board.products[0].partSkus[0].code, product.partSkus[0].code);
const crossPortfolioIdCollision = model.mergeChanges(twoPortfolios, [createProduct("p1", base, { categoryId: "console", laneId: "console-lane" })]);
assert.equal(crossPortfolioIdCollision.conflicts[0].reason, "product-id-exists", "internal product identities must remain globally unique even when business SKUs repeat");

const deleted = model.mergeChanges(manifest, [deleteProduct()], { requestId: "delete-request" });
assert.throws(() => model.mergeChanges(manifest, [{ ...deleteProduct(), baseProductVersion: undefined }]), /original master product version/);
assert.equal(deleted.savedProducts, 1);
assert.equal(deleted.history[0].kind, "delete");
assert.equal(deleted.history[0].beforeExists, true);
assert.equal(deleted.history[0].afterExists, false);
assert.equal(deleted.manifest.categories[0].board.products.length, 0);
assert.deepEqual(deleted.manifest.imageAssets, manifest.imageAssets, "deleting a product must not remove assets another product could still reference");
const deletedSnapshot = model.snapshot(deleted.manifest);
assert.deepEqual(deletedSnapshot.products, []);
assert.equal(deletedSnapshot.tombstones[0].productId, "p1");
assert.ok(deletedSnapshot.tombstones[0].revisions["@product"] > 0);
assert.deepEqual(deleted.manifest.masterSync.products.p1.archivedProduct, product, "private deletion metadata keeps the complete stored record for explicit restoration");
assert.equal(Object.hasOwn(deletedSnapshot.tombstones[0], "archivedProduct"), false, "public snapshots must not return the archived private product record");
assert.equal(model.mergeChanges(deleted.manifest, [deleteProduct()], { requestId: "other-delete" }).savedProducts, 0, "concurrent deletions converge once the product is removed");
const editAfterDelete = save(deleted.manifest, { name: "Keep my name" });
assert.equal(editAfterDelete.conflicts[0].reason, "product-removed");
assert.equal(editAfterDelete.conflicts[0].mine.name, "Keep my name");
assert.equal(editAfterDelete.conflicts[0].masterExists, false);
assert.equal(editAfterDelete.manifest, deleted.manifest);
assert.equal(model.mergeChanges(launch.manifest, [deleteProduct()]).conflicts[0].reason, "product-changed-before-delete", "a deletion cannot silently remove another user's date change");
assert.equal(model.mergeChanges(launchBack.manifest, [deleteProduct()]).conflicts[0].reason, "product-changed-before-delete", "away-and-back date edits must still conflict with an old deletion");
const nonsharedChanged = copy(manifest);
nonsharedChanged.categories[0].board.products[0].manualMetadata = "Another team's package note";
assert.equal(model.mergeChanges(nonsharedChanged, [deleteProduct()]).conflicts[0].reason, "product-changed-before-delete", "a deletion must notice changed full-record data outside the shared fields");
const changedImage = copy(manifest);
changedImage.categories[0].board.products[0].imageAssetId = "updated-image";
assert.equal(model.mergeChanges(changedImage, [deleteProduct()]).conflicts[0].reason, "product-changed-before-delete");
const acceptedDelete = model.mergeChanges(launch.manifest, [deleteProduct(model.snapshot(launch.manifest).products[0])]);
assert.equal(acceptedDelete.conflicts.length, 0, "explicitly confirming a deletion against the latest record allows it");
assert.equal(acceptedDelete.savedProducts, 1);

const staleRecreate = model.mergeChanges(deleted.manifest, [createProduct("p1", base)]);
assert.equal(staleRecreate.conflicts[0].reason, "product-removed", "a previously used identity cannot be restored without acknowledging its deletion revision");
const restored = model.mergeChanges(deleted.manifest, [createProduct("p1", base, { baseRevisions: deletedSnapshot.tombstones[0].revisions })], { requestId: "restore-request" });
assert.equal(restored.conflicts.length, 0);
assert.equal(restored.manifest.categories[0].board.products[0].id, "p1");
assert.equal(restored.manifest.categories[0].board.products[0].imageAssetId, product.imageAssetId);
assert.equal(restored.manifest.categories[0].board.products[0].featuredVariantId, product.featuredVariantId);
assert.equal(restored.manifest.categories[0].board.products[0].manualMetadata, product.manualMetadata);
assert.equal(restored.manifest.categories[0].board.products[0].roadmap.notes, product.roadmap.notes);
assert.equal(restored.manifest.categories[0].board.products[0].specs[0].manualNote, product.specs[0].manualNote);
assert.equal(restored.manifest.categories[0].board.products[0].partSkus[0].manualNote, product.partSkus[0].manualNote);
assert.equal(restored.manifest.categories[0].board.products[0].variantGroups[0].customSetting, product.variantGroups[0].customSetting);
assert.equal(restored.manifest.categories[0].board.products[0].variantGroups[0].items[0].imageAssetId, "local-black", "Keep mine restoration must retain each variant's original image reference");
assert.equal(Object.hasOwn(restored.manifest.masterSync.products.p1, "archivedProduct"), false, "a restored record no longer needs a duplicate archive copy");
assert.ok(model.snapshot(restored.manifest).products[0].revisions["@product"] > deletedSnapshot.tombstones[0].revisions["@product"]);
assert.equal(save(restored.manifest, { name: "Stale session name" }).conflicts[0].path, "name", "delete and recreate ABA must fence stale edits even when every shared value has returned to its original value");
assert.equal(model.mergeChanges(restored.manifest, [deleteProduct()]).conflicts[0].reason, "product-changed-before-delete");
const otherCreatedAfterDelete = model.mergeChanges(deleted.manifest, [createProduct()]);
assert.equal(model.snapshot(otherCreatedAfterDelete.manifest).tombstones[0].productId, "p1", "unrelated saves must retain removed-product revision fences");
assert.ok(model.snapshot(otherCreatedAfterDelete.manifest).products[0].revisions["@product"] > deletedSnapshot.tombstones[0].revisions["@product"]);

const mixedCreateConflict = model.mergeChanges(launch.manifest, [createProduct(), change({ generalAvailabilityDate: "2026-09-15" })]);
assert.equal(mixedCreateConflict.savedProducts, 0);
assert.equal(mixedCreateConflict.manifest, launch.manifest);
assert.equal(mixedCreateConflict.manifest.categories[0].board.products.length, 1, "a field conflict holds all creations in the same request");
const mixedDeleteConflict = model.mergeChanges(created.manifest, [deleteProduct(model.snapshot(created.manifest).products.find((entry) => entry.productId === "new-product")), change({ name: "Name accepted", generalAvailabilityDate: "2026-09-15" })]);
assert.equal(mixedDeleteConflict.conflicts.length, 0);
assert.equal(mixedDeleteConflict.savedProducts, 2, "independent deletion and edit can be committed in one atomic request");
assert.equal(mixedDeleteConflict.manifest.categories[0].board.products.length, 1);
const createdWithRemoteDate = save(created.manifest, { generalAvailabilityDate: "2026-07-01" });
const deleteAndStaleEdit = model.mergeChanges(createdWithRemoteDate.manifest, [deleteProduct(model.snapshot(createdWithRemoteDate.manifest).products.find((entry) => entry.productId === "new-product")), change({ generalAvailabilityDate: "2026-09-15" })]);
assert.equal(deleteAndStaleEdit.savedProducts, 0);
assert.equal(deleteAndStaleEdit.manifest, createdWithRemoteDate.manifest);
assert.equal(deleteAndStaleEdit.manifest.categories[0].board.products.length, 2, "a field conflict holds every deletion in the same request");
const concurrentDistinctCreates = model.mergeChanges(created.manifest, [createProduct("another-product", { ...base, name: "Another team product" })]);
assert.equal(concurrentDistinctCreates.conflicts.length, 0);
assert.deepEqual(concurrentDistinctCreates.manifest.categories[0].board.products.map((entry) => entry.id), ["p1", "new-product", "another-product"]);
assert.equal(concurrentDistinctCreates.manifest.categories[0].board.products[2].order, 1, "independent new products append safely after accepted lane records");

const blackRed = { id: "black-red", code: "BK", colorKey: "black", colorName: "Black", colorHex: "#111111", colorKey2: "red", colorName2: "Red", colorHex2: "#b72f3d" };
const redBlack = { id: "red-black", code: "BK", colorKey: "red", colorName: "Red", colorHex: "#b72f3d", colorKey2: "black", colorName2: "Black", colorHex2: "#111111" };
const singleRed = { id: "red", code: "RD", colorKey: "red", colorName: "Red", colorHex: "#b72f3d" };
const allColorways = copy(base.variantGroups);
allColorways[0].items.push(blackRed, redBlack, singleRed, { ...blackRed, id: "explicit-black-red", code: "BK/RD" });
const colorwaySaved = save(manifest, { variantGroups: allColorways });
assert.equal(colorwaySaved.conflicts.length, 0, "BK single, BK with a secondary red, reversed red/black, RD, and BK/RD codes are distinct assignments");
assert.equal(savedProduct(colorwaySaved).variantGroups[0].items.length, 5);
assert.match(model.describeNode(blackRed), /Black \/ Red/, "conflict descriptions expose both colors");
const dualMaster = copy(base.variantGroups), reversedMine = copy(base.variantGroups);
dualMaster[0].items.push(blackRed); reversedMine[0].items.push(redBlack);
const separateDualAdds = save(save(manifest, { variantGroups: dualMaster }).manifest, { variantGroups: reversedMine });
assert.equal(separateDualAdds.conflicts.length, 0, "different ordered colorways added concurrently can share the same display code");
assert.equal(savedProduct(separateDualAdds).variantGroups[0].items.length, 3);
const sameDualMine = copy(base.variantGroups);
sameDualMine[0].items.push({ ...blackRed, id: "another-black-red", code: " bk " });
const sameDualConflict = save(save(manifest, { variantGroups: dualMaster }).manifest, { variantGroups: sameDualMine });
assert.equal(sameDualConflict.conflicts[0].reason, "duplicate-sku", "an exact same code and color combination added by another team still requires a choice");
assert.match(sameDualConflict.conflicts[0].label, /colorway/i);
assert.match(sameDualConflict.conflicts[0].masterText, /Black \/ Red/);
assert.throws(() => model.patchValues(base, { variantGroups: [{ id: "duplicate-colorways", type: "color", items: [blackRed, { ...blackRed, id: "duplicate" }] }] }), /same colorway code/);
assert.throws(() => model.patchValues(base, { variantGroups: [{ id: "duplicate-layouts", type: "layout", items: [{ id: "us-a", code: "US", label: "United States" }, { id: "us-b", code: " us ", label: "Different label" }] }] }), /same SKU code/);
assert.throws(() => model.patchValues(base, { partSkus: [...base.partSkus, { ...base.partSkus[0], id: "duplicate-part", variantId: "another-colorway" }] }), /same SKU code/, "business HP SKU rows must stay unique even when assigned to different colors");
assert.equal(model.variantSkuIdentity({ code: "CUSTOM", colorHex: "#AbC" }, "color"), model.variantSkuIdentity({ code: "custom", colorHex: "#aabbcc" }, "color"), "equivalent short/full hex notation identifies the same colorway");
const colorEditBaseProduct = { ...copy(product), variantGroups: [{ ...copy(product.variantGroups[0]), items: [copy(product.variantGroups[0].items[0]), redBlack] }] };
const colorEditManifest = copy(manifest); colorEditManifest.categories[0].board.products[0] = colorEditBaseProduct;
const colorEditBase = model.productValues(colorEditBaseProduct);
const remoteColorChange = colorEditBase.variantGroups.map((group) => ({ ...group, items: group.items.map((row) => row.id === "red-black" ? { ...blackRed, id: row.id } : row) }));
const localColorChange = colorEditBase.variantGroups.map((group) => ({ ...group, items: group.items.map((row) => row.id === "black" ? { ...blackRed, id: row.id } : row) }));
const remoteColorSaved = save(colorEditManifest, { variantGroups: remoteColorChange }, colorEditBase);
const colorEditConflict = save(remoteColorSaved.manifest, { variantGroups: localColorChange }, colorEditBase);
assert.equal(colorEditConflict.conflicts[0].path, "variantGroups/colors/items/black", "a same-code color change collision must identify the locally edited row instead of arbitrarily selecting the remote row");
assert.equal(colorEditConflict.conflicts[0].reason, "duplicate-sku");

const reviewedWhite = { id: "reviewed-white", code: "WHT", colorName: "White", colorHex: "#ffffff" };
const colorwayPlc = { version: 1, variantProjects: { "reviewed-white": { version: 1, variantId: "reviewed-white", fields: { ffsDate: { value: "2027-04-01", changedAt: "2026-10-09T16:00:00.000Z" } } } },
  identities: [{ key: "source-white", variantId: "reviewed-white", confirmed: true }] };
const colorwayBase = model.patchValues(base, { variantGroups: [{ ...copy(base.variantGroups[0]), items: [...copy(base.variantGroups[0].items), reviewedWhite] }], plc: colorwayPlc });
const removedWhite = model.patchValues(colorwayBase, { variantGroups: base.variantGroups });
const nextColorwayPlc = copy(colorwayPlc); nextColorwayPlc.variantProjects["reviewed-white"].fields.ffsDate.value = "2028-04-01";
const colorwayMine = model.patchValues(colorwayBase, { plc: nextColorwayPlc });
const removedColorwayPlan = model.planMerge(colorwayBase, colorwayMine, removedWhite);
assert.equal(removedColorwayPlan.conflicts.length, 1); assert.equal(removedColorwayPlan.conflicts[0].path, "plc");
assert.equal(removedColorwayPlan.conflicts[0].reason, "removed-colorway"); assert.deepEqual(removedColorwayPlan.conflicts[0].variantIds, ["reviewed-white"]);
assert.deepEqual(removedColorwayPlan.values.plc, removedWhite.plc, "A deleted colorway keeps the safe master evidence instead of publishing new dangling dates.");
assert.deepEqual(model.resolveConflicts(removedColorwayPlan, { plc: "master" }).plc, colorwayPlc);
const variantManifest = copy(manifest); variantManifest.categories[0].board.products[0] = model.applyProductValues(product, colorwayBase);
const removedVariantResult = save(variantManifest, { variantGroups: base.variantGroups }, colorwayBase);
assert.equal(removedVariantResult.conflicts.length, 0, "Ordinary colorway deletion preserves readable historical evidence.");
assert.equal(model.snapshot(removedVariantResult.manifest).products[0].values.plc.variantProjects["reviewed-white"].fields.ffsDate.value, "2027-04-01");
const lateVariantEvidence = save(removedVariantResult.manifest, { plc: nextColorwayPlc }, colorwayBase);
assert.equal(lateVariantEvidence.conflicts[0].reason, "removed-colorway"); assert.deepEqual(lateVariantEvidence.manifest, removedVariantResult.manifest, "The server rejects the entire late save after a row deletion.");
const preservedOrphan = copy(colorwayPlc); preservedOrphan.fields = { ffsDate: { value: "2027-03-01" } };
assert.equal(save(removedVariantResult.manifest, { plc: preservedOrphan }, removedWhite).conflicts.length, 0, "A parent date evidence update may retain unchanged legacy orphan evidence.");
const unconfirmed = { version: 1, identities: [{ key: "pending-colorway", variantId: "missing-color", confirmed: false }] };
assert.equal(model.planMerge(base, model.patchValues(base, { plc: unconfirmed }), base).conflicts.length, 0, "Unconfirmed source observations remain collectable for later review.");
const confirmed = copy(unconfirmed); confirmed.identities[0].confirmed = true;
assert.equal(model.planMerge(base, model.patchValues(base, { plc: confirmed }), base).conflicts[0].reason, "removed-colorway", "A new confirmed binding requires a matching color row even without date fields.");
const newColorway = model.planMerge(base, colorwayMine, base);
assert.equal(newColorway.conflicts.length, 0, "A reviewed row and its PLC evidence can be added atomically.");
assert.equal(newColorway.values.plc.variantProjects["reviewed-white"].fields.ffsDate.value, "2028-04-01");
const layoutOnly = model.patchValues(base, { variantGroups: [{ id: "layouts", type: "layout", label: "Layouts", items: [{ id: "reviewed-white", code: "US", label: "United States" }] }] });
assert.equal(model.planMerge(layoutOnly, model.patchValues(layoutOnly, { plc: nextColorwayPlc }), layoutOnly).conflicts[0].reason, "removed-colorway", "A layout row cannot satisfy a colorway evidence match.");
assert.throws(() => model.resolveConflicts(removedColorwayPlan, { plc: "mine" }), /review the source match/, "A removed colorway requires a fresh source-match review; choosing mine cannot recreate dangling evidence.");
const whitePinkRows = copy(colorwayBase.variantGroups); whitePinkRows[0].items.find(row => row.id === "reviewed-white").colorName2 = "Pink";
whitePinkRows[0].items.find(row => row.id === "reviewed-white").colorKey2 = "pink"; whitePinkRows[0].items.find(row => row.id === "reviewed-white").colorHex2 = "#ff88aa";
const whitePinkMaster = model.patchValues(colorwayBase, { variantGroups: whitePinkRows });
const changedColorwayPlan = model.planMerge(colorwayBase, colorwayMine, whitePinkMaster);
assert.equal(changedColorwayPlan.conflicts[0].reason, "changed-colorway");
assert.deepEqual(changedColorwayPlan.values.plc, colorwayPlc, "A stable row ID cannot publish White-only dates after its identity changes to White/Pink.");
assert.throws(() => model.resolveConflicts(changedColorwayPlan, { plc: "mine" }), /review the source match/);
assert.deepEqual(model.resolveConflicts(changedColorwayPlan, { plc: "master" }).plc, colorwayPlc);
const preview = model.resolveConflicts(changedColorwayPlan, { plc: "mine" }, { preserveDrafts: true });
assert.equal(preview.plc.variantProjects["reviewed-white"].fields.ffsDate.value, "2028-04-01", "A read-only preview retains the local date draft.");
assert.equal(preview.variantGroups[0].items.find(row => row.id === "reviewed-white").colorName2, "Pink", "The preview still receives the current master row.");
assert.equal(preview.plc.variantProjects["reviewed-white"].colorway.colorName, "White", "Legacy preview seals its original reviewed row before that row changes.");
assert.equal(preview.plc.variantProjects["reviewed-white"].colorway.colorName2, "");
const previewRetry = model.planMerge(whitePinkMaster, preview, whitePinkMaster);
assert.equal(previewRetry.conflicts[0].reason, "changed-colorway", "A refreshed baseline/current row cannot redefine a retained draft's source identity.");
assert.throws(() => model.resolveConflicts(previewRetry, { plc: "mine" }), /review the source match/, "Draft preview permission does not carry into normal merge decisions.");
const snapshotDraft = copy(nextColorwayPlc); snapshotDraft.variantProjects["reviewed-white"].colorway = { code: "WHT", colorKey: "", colorName: "White", colorHex: "#ffffff", colorKey2: "", colorName2: "", colorHex2: "" };
const stableSnapshotPlan = model.planMerge(whitePinkMaster, model.patchValues(whitePinkMaster, { plc: snapshotDraft }), whitePinkMaster);
assert.equal(stableSnapshotPlan.conflicts[0].reason, "changed-colorway", "An explicit reviewed snapshot binds source evidence even when all current rows and baselines already changed.");
const cosmeticRows = copy(colorwayBase.variantGroups), cosmeticWhite = cosmeticRows[0].items.find(row => row.id === "reviewed-white");
cosmeticWhite.label = "Accepted White finish"; cosmeticWhite.colorName = "Accepted White name"; cosmeticWhite.colorHex = "#eeeeee";
assert.equal(model.planMerge(colorwayBase, colorwayMine, model.patchValues(colorwayBase, { variantGroups: cosmeticRows })).conflicts.length, 0, "Known White identity survives cosmetic accepted names and swatch refinements.");
assert.equal(model.variantMatchIdentity({ code: "white", colorKey: "white", colorName: "White", colorHex: "#fff" }), model.variantMatchIdentity({ code: " WT ", colorKey: "WHITE", colorName: "White finish", colorHex: "#eeeeee" }));
assert.notEqual(model.variantMatchIdentity({ code: "WHT", colorName: "White" }), model.variantMatchIdentity({ code: "WHT", colorName: "White", colorName2: "Pink" }));
assert.notEqual(model.variantMatchIdentity({ code: "WHT", colorName: "White", colorKey: "white" }), model.variantMatchIdentity({ code: "WHT", colorName: "White", colorKey: "pink" }), "Conflicting normalized color keys require review even when names are unchanged.");
assert.notEqual(model.variantMatchIdentity({ code: "CUSTOM", colorName: "Ocean", colorHex: "#123456" }), model.variantMatchIdentity({ code: "CUSTOM", colorName: "Ocean", colorHex: "#654321" }));
assert.equal(model.variantMatchIdentity({ code: "CUSTOM", colorName: "Ocean", colorHex: "#abc" }), model.variantMatchIdentity({ code: "custom", colorName: " ocean ", colorHex: "#aabbcc" }));

console.log("Shared master model checks passed: granular merges, explicit lifecycle choices and replay protection, full-record deletion versions, portfolio-scoped copies, ABA revisions, image preservation, safe draft baselines, bounded history, and removed-colorway PLC guards with legacy evidence compatibility.");
